CREATE TABLE EVENT
(
  id INT(11) NOT NULL AUTO_INCREMENT,
  topic VARCHAR(50) NOT NULL,
  context VARCHAR(200) DEFAULT NULL,
  isSuccess TINYINT DEFAULT NULL,
  consumerNums INT DEFAULT NULL ,
  gmtCreate DATETIME DEFAULT NULL ,
  gmtModified DATETIME DEFAULT NULL ,
  PRIMARY KEY (ID)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=LATIN1;
