CREATE TABLE EVENT
(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TOPIC VARCHAR(50) NOT NULL,
  PROCESSOR VARCHAR(50) NOT NULL,
  CONTEXT VARCHAR(15) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=LATIN1;
